# Generated by Django 2.1.1 on 2018-09-23 11:20
#manually added custom SQL

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_v_ordrelinje'),
    ]

    operations = [
        migrations.AddField(
            model_name='vare',
            name='produktaar',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vare',
            name='produktkategori',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vare',
            name='produktopprinnelse',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vare',
            name='produkttype',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
     ]
