# Generated by Django 2.1.1 on 2018-09-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180904_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ship_date',
            field=models.DateField(),
        ),
    ]
